# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Install Packages
      run: yarn install    
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - run: zip -r maven.zip . -i maven 
    - uses: actions/upload-artifact@v3
      with:
           name: node
           path: maven.zip
      
  deploy:
    runs-on: ubuntu-latest
    needs: build     
    steps: 
    - uses: actions/checkout@v3
    - name: set up jdk 11
      uses: actions/setup-java@v3
      with: 
          java-version: '11'
          distribution: 'adopt'
          cache: maven
    - name: Create SSH key
      run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/id_rsa     
    - uses: actions/download-artifact@v3
      with:
          name: node
          path: maven.zip
    - run: ls -al
    - run: |
         scp -r maven.zip ${{ secrets.SSH_USER }}@${{ secrets.SSH_KNOWN_HOSTS }}:~/vprofile

     
